// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRyuOGyM3no6VhAIw1upy6ND6J6-sW86s',
    appId: '1:33746456705:web:80c1c20859a19690cb3d80',
    messagingSenderId: '33746456705',
    projectId: 'groceries-app-3aefc',
    authDomain: 'groceries-app-3aefc.firebaseapp.com',
    storageBucket: 'groceries-app-3aefc.appspot.com',
    measurementId: 'G-0PBNHH3MME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlnliAFWZqcBEU0nEbrU-sYbDhvXWK08',
    appId: '1:33746456705:android:3301c31dc4496d74cb3d80',
    messagingSenderId: '33746456705',
    projectId: 'groceries-app-3aefc',
    storageBucket: 'groceries-app-3aefc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprotL9cLuaKitYSifSq1zH3o7BuvlfGk',
    appId: '1:33746456705:ios:4ba8d66db5f8ce58cb3d80',
    messagingSenderId: '33746456705',
    projectId: 'groceries-app-3aefc',
    storageBucket: 'groceries-app-3aefc.appspot.com',
    androidClientId: '33746456705-i4cntme0lcdvopb119ela4vics7f68sp.apps.googleusercontent.com',
    iosClientId: '33746456705-drcsdinaibcclvdhj0j6dgva34k56kd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDprotL9cLuaKitYSifSq1zH3o7BuvlfGk',
    appId: '1:33746456705:ios:4ba8d66db5f8ce58cb3d80',
    messagingSenderId: '33746456705',
    projectId: 'groceries-app-3aefc',
    storageBucket: 'groceries-app-3aefc.appspot.com',
    androidClientId: '33746456705-i4cntme0lcdvopb119ela4vics7f68sp.apps.googleusercontent.com',
    iosClientId: '33746456705-drcsdinaibcclvdhj0j6dgva34k56kd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRyuOGyM3no6VhAIw1upy6ND6J6-sW86s',
    appId: '1:33746456705:web:f1914203450a8e4bcb3d80',
    messagingSenderId: '33746456705',
    projectId: 'groceries-app-3aefc',
    authDomain: 'groceries-app-3aefc.firebaseapp.com',
    storageBucket: 'groceries-app-3aefc.appspot.com',
    measurementId: 'G-E28LF5Q56Z',
  );
}
